# Generated by Django 4.1.7 on 2023-06-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Residential'), (2, 'Commercial'), (3, ' Main Commercial')])),
                ('size_type', models.IntegerField(choices=[(1, 'sq ft'), (2, 'Marla')])),
                ('size', models.FloatField()),
                ('rate', models.FloatField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/plots')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
            ],
            options={
                'db_table': 'plots',
            },
        ),
    ]
