# Generated by Django 4.1.7 on 2023-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plots',
            name='size',
        ),
        migrations.RemoveField(
            model_name='plots',
            name='size_type',
        ),
        migrations.AddField(
            model_name='plots',
            name='marlas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plots',
            name='square_feets',
            field=models.FloatField(default=0),
        ),
    ]
