# Generated by Django 4.1.7 on 2023-06-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_remove_plots_size_remove_plots_size_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plots',
            old_name='square_feets',
            new_name='square_fts',
        ),
    ]
