# Generated by Django 4.1.7 on 2023-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0003_rename_square_feets_plots_square_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
