# Generated by Django 4.1.7 on 2024-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0006_remove_plots_pic_plots_parent_plot_alter_plots_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
