# Generated by Django 4.1.7 on 2024-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0007_plots_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='rate_marla',
            field=models.FloatField(default=0),
        ),
    ]
