# Generated by Django 4.1.7 on 2024-08-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0008_plots_rate_marla'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plotsdocuments',
            table='plots_documents',
        ),
    ]
