# Generated by Django 4.1.7 on 2024-10-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_alter_plotsdocuments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
    ]
