# Generated by Django 4.1.7 on 2024-11-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0010_plots_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='plots',
            name='block',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
