# Generated by Django 4.1.7 on 2023-06-19 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('payments', '0002_paymentreminder'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentreminder',
            table='payments_reminder',
        ),
        migrations.CreateModel(
            name='ExpensePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
            ],
            options={
                'db_table': 'expense_persons',
            },
        ),
    ]
