# Generated by Django 4.1.7 on 2024-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_outgoingfund_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingfund',
            name='advnace_payment',
            field=models.BooleanField(default=False),
        ),
    ]
