# Generated by Django 4.1.7 on 2024-05-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_bank_incomingfund_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingfund',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.bank'),
            preserve_default=False,
        ),
    ]
