# Generated by Django 4.1.7 on 2024-05-22 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_incomingfund_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingfund',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outgoingfund',
            name='payment_type',
            field=models.CharField(default='cash', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OutgoingFundDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/dealer_files')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='payments.outgoingfund')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingFundDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/dealer_files')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='payments.incomingfund')),
            ],
        ),
    ]
