# Generated by Django 4.1.7 on 2024-05-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_outgoingfund_bank_outgoingfund_payment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingfunddocuments',
            old_name='dealer',
            new_name='incoming_fund',
        ),
        migrations.RenameField(
            model_name='outgoingfunddocuments',
            old_name='dealer',
            new_name='incoming_fund',
        ),
    ]
