# Generated by Django 4.1.7 on 2024-05-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_rename_dealer_incomingfunddocuments_incoming_fund_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoingfunddocuments',
            old_name='incoming_fund',
            new_name='outgoing_fund',
        ),
    ]
