# Generated by Django 4.1.7 on 2024-05-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_rename_incoming_fund_outgoingfunddocuments_outgoing_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingfund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bank'),
        ),
        migrations.AlterField(
            model_name='incomingfund',
            name='payment_type',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='outgoingfund',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.bank'),
        ),
        migrations.AlterField(
            model_name='outgoingfund',
            name='payment_type',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
