# Generated by Django 4.1.7 on 2024-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_incomingfund_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingfunddocuments',
            name='file',
            field=models.FileField(upload_to='media/payments_files'),
        ),
    ]
