# Generated by Django 4.1.7 on 2024-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_incomingfunddocuments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_type',
            field=models.CharField(default='bank', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='detail_type',
            field=models.CharField(default='check', max_length=30),
            preserve_default=False,
        ),
    ]
