# Generated by Django 4.1.7 on 2024-06-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_bank_parent_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('deposit_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.bank')),
                ('deposit_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankDepositDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/payments_files')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='payments.bankdeposit')),
            ],
        ),
        migrations.CreateModel(
            name='BankDepositDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payments.bankdeposit')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.incomingfund')),
            ],
        ),
    ]
