# Generated by Django 4.1.7 on 2024-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_bankdeposit_bankdepositdocuments_bankdepositdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='deposit_from',
        ),
        migrations.AddField(
            model_name='incomingfund',
            name='reference',
            field=models.CharField(default='payment', max_length=10),
        ),
    ]
