# Generated by Django 4.1.7 on 2024-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_remove_bankdeposit_deposit_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bank',
            name='detail_type',
            field=models.CharField(max_length=100),
        ),
    ]
