# Generated by Django 4.1.7 on 2024-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_alter_bank_account_type_alter_bank_detail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
