# Generated by Django 4.1.7 on 2024-06-12 11:41

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customersdocuments_file'),
        ('projects', '0005_rename_details_balancesheetamountdetails_detail'),
        ('payments', '0021_alter_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDepositTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='payment', max_length=10)),
                ('date', models.DateField()),
                ('installement_month', payments.models.MonthField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(default='cash', max_length=20)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.bank')),
                ('bank_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.bankdeposit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
            ],
        ),
    ]
