# Generated by Django 4.1.7 on 2024-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_bankdeposit_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='amount',
            new_name='deposit',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
