# Generated by Django 4.1.7 on 2024-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_alter_banktransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingfund',
            name='deposit',
            field=models.BooleanField(default=False),
        ),
    ]
