# Generated by Django 4.1.7 on 2024-07-09 20:22

from django.db import migrations
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_incomingfund_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingfund',
            name='installement_month',
            field=payments.models.MonthField(blank=True, null=True),
        ),
    ]
