# Generated by Django 4.1.7 on 2024-07-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customersdocuments_file'),
        ('payments', '0031_alter_incomingfund_installement_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposittransactions',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customers'),
        ),
    ]
