# Generated by Django 4.1.7 on 2024-07-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_details_balancesheetamountdetails_detail'),
        ('booking', '0028_plotresale_date'),
        ('payments', '0032_alter_bankdeposittransactions_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='payment', max_length=10)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_type', models.CharField(default='cash', max_length=20)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('deposit', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_payments', to='payments.bank')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
            ],
            options={
                'db_table': 'dealer_payments',
            },
        ),
        migrations.CreateModel(
            name='DealerPaymentsDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/dealer_payments_files')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='payments.dealerpayments')),
            ],
        ),
    ]
