# Generated by Django 4.1.7 on 2024-07-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_dealerpayments_dealerpaymentsdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealerpayments',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='incomingfund',
            name='deposit',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_deposit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankdepositdetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.banktransaction'),
        ),
    ]
