# Generated by Django 4.1.7 on 2024-08-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_details_balancesheetamountdetails_detail'),
        ('payments', '0035_journalentry_journalentryline_journalentrydocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfer', to='payments.bank')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_received', to='payments.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransferDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/bank_transfer_files')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='payments.banktransfer')),
            ],
        ),
    ]
