# Generated by Django 4.1.7 on 2024-08-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_customers_gender_customers_joining_date_and_more'),
        ('payments', '0036_banktransfer_banktransferdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingfund',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='outgoingfund',
            name='person',
        ),
        migrations.AddField(
            model_name='outgoingfund',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.customers'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OutgoingFundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_details', to='payments.bank')),
                ('outgoing_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payments.outgoingfund')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customers')),
            ],
        ),
    ]
