# Generated by Django 4.1.7 on 2024-08-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_remove_outgoingfund_expense_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='reference',
        ),
    ]
