# Generated by Django 4.1.7 on 2024-08-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_remove_journalentry_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='debit',
            field=models.FloatField(default=0),
        ),
    ]
