# Generated by Django 4.1.7 on 2024-08-21 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_customers_father_name'),
        ('payments', '0039_alter_journalentryline_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentryline',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='customer.customers'),
        ),
    ]
