# Generated by Django 4.1.7 on 2024-08-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_remove_bankdeposittransactions_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
