# Generated by Django 4.1.7 on 2024-08-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_alter_banktransaction_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposittransactions',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='bankdeposittransactions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bankdeposittransactions',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='bankdeposittransactions',
            name='project',
        ),
    ]
