# Generated by Django 4.1.7 on 2024-08-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_remove_bankdeposittransactions_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='is_cheque_clear',
            field=models.BooleanField(default=True),
        ),
    ]
