# Generated by Django 4.1.7 on 2024-08-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0044_banktransaction_is_cheque_clear'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeClearanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_clearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payments.chequeclearance')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.banktransaction')),
            ],
        ),
    ]
