# Generated by Django 4.1.7 on 2024-08-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_chequeclearancedocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingfunddetails',
            name='person',
        ),
    ]
