# Generated by Django 4.1.7 on 2024-08-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0047_remove_outgoingfunddetails_person'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
        migrations.AlterModelTable(
            name='bankdepositdocuments',
            table='bank_deposits_documents',
        ),
        migrations.AlterModelTable(
            name='bankdeposittransactions',
            table='bank_deposits_details',
        ),
        migrations.AlterModelTable(
            name='banktransaction',
            table='bank_transactions',
        ),
        migrations.AlterModelTable(
            name='banktransfer',
            table='bank_transfer',
        ),
        migrations.AlterModelTable(
            name='banktransferdocuments',
            table='bank_transfer_documents',
        ),
        migrations.AlterModelTable(
            name='chequeclearance',
            table='cheque_clearance',
        ),
        migrations.AlterModelTable(
            name='chequeclearancedetail',
            table='cheque_clearance_details',
        ),
        migrations.AlterModelTable(
            name='chequeclearancedocuments',
            table='cheque_clearance_documents',
        ),
        migrations.AlterModelTable(
            name='dealerpaymentsdocuments',
            table='dealer_payments_documents',
        ),
        migrations.AlterModelTable(
            name='incomingfunddocuments',
            table='incoming_funds_documents',
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='journal_entry',
        ),
        migrations.AlterModelTable(
            name='journalentrydocuments',
            table='journal_entry_documents',
        ),
        migrations.AlterModelTable(
            name='journalentryline',
            table='journal_entry_details',
        ),
        migrations.AlterModelTable(
            name='outgoingfunddetails',
            table='outgoing_funds_details',
        ),
        migrations.AlterModelTable(
            name='outgoingfunddocuments',
            table='outgoing_funds_documents',
        ),
    ]
