# Generated by Django 4.1.7 on 2024-08-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0048_alter_bank_table_alter_bankdepositdocuments_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankdeposittransactions',
            table='bank_deposits_transactions',
        ),
    ]
