# Generated by Django 4.1.7 on 2024-09-07 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_customermessages_table_and_more'),
        ('payments', '0050_alter_bankdepositdetail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingfund',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customers'),
        ),
    ]
