# Generated by Django 4.1.7 on 2024-09-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0051_alter_outgoingfund_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='deposit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='payment',
            field=models.FloatField(default=0),
        ),
    ]
