# Generated by Django 4.2.16 on 2024-09-28 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_details_balancesheetamountdetails_detail'),
        ('payments', '0052_alter_banktransaction_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='projects.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='projects.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='projects.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequeclearance',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='projects.projects'),
            preserve_default=False,
        ),
    ]
