# Generated by Django 4.1.7 on 2024-10-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0053_bank_project_bankdeposit_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='used_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
