# Generated by Django 4.1.7 on 2024-10-22 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0054_bank_used_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposittransactions',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
