# Generated by Django 4.1.7 on 2024-11-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0010_plots_cost_price'),
        ('payments', '0055_bankdeposittransactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingfund',
            name='reference_plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plots.plots'),
        ),
    ]
