# Generated by Django 4.1.7 on 2024-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0056_incomingfund_reference_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
    ]
