# Generated by Django 4.1.7 on 2024-11-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0057_bankdeposit_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingfund',
            name='document_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
