# Generated by Django 4.1.7 on 2024-11-28 00:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0058_incomingfund_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingfund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingfund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
