# Generated by Django 4.1.7 on 2024-03-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectsbalancesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsbalancesheet',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='projectsbalancesheet',
            name='project',
        ),
        migrations.CreateModel(
            name='BalanceSheetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_detail', to='projects.projectsbalancesheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
            ],
        ),
    ]
