# Generated by Django 4.1.7 on 2024-03-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_remove_projectsbalancesheet_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheetAmountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='projects.balancesheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectsbalancesheet',
            name='user',
        ),
        migrations.DeleteModel(
            name='BalanceSheetDetail',
        ),
        migrations.DeleteModel(
            name='ProjectsBalanceSheet',
        ),
        migrations.AddField(
            model_name='balancesheetamountdetails',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_details', to='projects.balancesheetdetails'),
        ),
        migrations.AddField(
            model_name='balancesheetamountdetails',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects'),
        ),
    ]
