# Generated by Django 4.1.7 on 2024-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_balancesheet_balancesheetamountdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheetamountdetails',
            old_name='details',
            new_name='detail',
        ),
    ]
