# Generated by Django 4.1.7 on 2023-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customermessages_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessagesdocuments',
            name='type',
            field=models.CharField(default='audio', max_length=20),
            preserve_default=False,
        ),
    ]
