# Generated by Django 4.1.7 on 2024-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customermessagesdocuments_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessages',
            name='follow_up',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customermessages',
            name='follow_up_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
