# Generated by Django 4.1.7 on 2024-03-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_plotresale_booking'),
        ('customer', '0009_alter_customermessages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessages',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.booking'),
        ),
    ]
