# Generated by Django 4.1.7 on 2024-03-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customermessages_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermessages',
            name='plot',
        ),
    ]
