# Generated by Django 4.1.7 on 2024-05-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_details_balancesheetamountdetails_detail'),
        ('customer', '0011_remove_customermessages_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(blank=True, max_length=40, null=True)),
                ('cnic', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='DealersDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/dealer_files')),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='customer.dealers')),
            ],
        ),
    ]
