# Generated by Django 4.1.7 on 2024-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customersdocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersdocuments',
            name='file',
            field=models.FileField(upload_to='media/customer_files'),
        ),
    ]
