# Generated by Django 4.1.7 on 2024-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customers_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
