# Generated by Django 4.1.7 on 2024-08-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_customers_gender_customers_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
