# Generated by Django 4.1.7 on 2023-06-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='installement_date',
            new_name='installment_date',
        ),
    ]
