# Generated by Django 4.1.7 on 2023-06-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_remaining_amount',
        ),
    ]
