# Generated by Django 4.1.7 on 2023-06-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_plots_status'),
        ('booking', '0004_remove_booking_total_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_details', to='plots.plots'),
        ),
    ]
