# Generated by Django 4.1.7 on 2023-10-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('booking', '0006_alter_booking_created_at_alter_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotResale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('project_amount_paid', models.FloatField()),
                ('customer_amount_paid', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
                ('current_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projects')),
                ('old_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resale_plots', to='projects.projects')),
            ],
        ),
    ]
