# Generated by Django 4.1.7 on 2023-10-27 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0004_plots_status'),
        ('booking', '0007_plotresale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotresale',
            name='current_project',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='old_project',
        ),
        migrations.AddField(
            model_name='plotresale',
            name='plot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='resale_plots', to='plots.plots'),
            preserve_default=False,
        ),
    ]
