# Generated by Django 4.1.7 on 2024-01-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_plotresale_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plotresale',
            old_name='amount_paid',
            new_name='company_amount_paid',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='project_amount_paid',
        ),
        migrations.AddField(
            model_name='plotresale',
            name='company_profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotresale',
            name='customer_profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotresale',
            name='entry_type',
            field=models.CharField(default='resale', max_length=10),
        ),
        migrations.AddField(
            model_name='plotresale',
            name='new_plot_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotresale',
            name='old_plot_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotresale',
            name='per_marla_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
