# Generated by Django 4.1.7 on 2024-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_amount_paid_plotresale_company_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotresale',
            name='company_amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotresale',
            name='company_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotresale',
            name='customer_amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotresale',
            name='customer_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotresale',
            name='new_plot_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotresale',
            name='old_plot_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotresale',
            name='per_marla_price',
            field=models.FloatField(default=0),
        ),
    ]
