# Generated by Django 4.1.7 on 2024-03-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_booking_type_booking_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotresale',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
