# Generated by Django 4.1.7 on 2024-05-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_dealers_dealersdocuments'),
        ('booking', '0013_alter_plotresale_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.dealers'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dealer_comission_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='dealer_comission_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='dealer_per_marla_comission',
            field=models.FloatField(default=0),
        ),
    ]
