# Generated by Django 4.1.7 on 2024-05-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_dealers_dealersdocuments'),
        ('booking', '0014_booking_dealer_booking_dealer_comission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customer.dealers'),
        ),
    ]
