# Generated by Django 4.1.7 on 2024-05-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_bookingdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comission_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
    ]
