# Generated by Django 4.1.7 on 2024-05-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_comission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reference_contact',
        ),
    ]
