# Generated by Django 4.1.7 on 2024-05-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_remove_booking_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comission_type',
            field=models.CharField(blank=True, default='percentage', max_length=20, null=True),
        ),
    ]
