# Generated by Django 4.1.7 on 2024-05-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_booking_comission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdocuments',
            name='file',
            field=models.FileField(upload_to='media/booking_files'),
        ),
    ]
