# Generated by Django 4.1.7 on 2024-06-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_bankdeposit_bankdepositdocuments_bankdepositdetail'),
        ('booking', '0020_alter_bookingdocuments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='token_payments', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='token',
            name='payment_type',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
