# Generated by Django 4.1.7 on 2024-07-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_bankdeposittransactions_cheque_number_and_more'),
        ('booking', '0022_token_cheque_number_tokendocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='payments.bank'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
