# Generated by Django 4.1.7 on 2024-07-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_booking_bank_booking_cheque_number_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='token',
            table='token',
        ),
    ]
