# Generated by Django 4.1.7 on 2024-07-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_customersdocuments_file'),
        ('booking', '0024_alter_token_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customer.customers'),
        ),
    ]
