# Generated by Django 4.1.7 on 2024-07-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_alter_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotresale',
            name='customer_amount_paid',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='entry_type',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='new_plot_price',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='old_plot_price',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='per_marla_price',
        ),
        migrations.RemoveField(
            model_name='plotresale',
            name='plot',
        ),
    ]
