# Generated by Django 4.1.7 on 2024-07-31 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_booking_plot_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plot_amount',
        ),
    ]
