# Generated by Django 4.1.7 on 2024-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_remove_booking_plot_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='plot_amount',
            field=models.FloatField(default=0),
        ),
    ]
