# Generated by Django 4.1.7 on 2024-08-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_token_plot_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='booking.token'),
        ),
    ]
