# Generated by Django 4.1.7 on 2024-08-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_department_customers_department'),
        ('booking', '0034_alter_token_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_bookings', to='customer.customers'),
        ),
    ]
