# Generated by Django 4.1.7 on 2024-08-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_alter_booking_dealer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingdocuments',
            table='booking_documents',
        ),
        migrations.AlterModelTable(
            name='plotresale',
            table='plot_resale',
        ),
        migrations.AlterModelTable(
            name='tokendocuments',
            table='token_documents',
        ),
    ]
