# Generated by Django 4.1.7 on 2024-10-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_booking_new_plots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='plot',
        ),
    ]
