# Generated by Django 4.1.7 on 2024-10-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_remove_booking_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='new_plots',
            new_name='plots',
        ),
    ]
