# Generated by Django 4.1.7 on 2024-10-03 15:53

from django.db import migrations, models

def transfer_plot_to_plots(apps, schema_editor):
    Token = apps.get_model('booking', 'Token')
    for token in Token.objects.all():
        if token.plot:
            token.new_plot.add(token.plot)

class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0009_alter_plotsdocuments_table'),
        ('booking', '0039_rename_new_plots_booking_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='new_plot',
            field=models.ManyToManyField(related_name='tokens', to='plots.plots'),
        ),
        migrations.RunPython(transfer_plot_to_plots),
    ]
