# Generated by Django 4.1.7 on 2024-10-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_token_new_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='plot',
        ),
    ]
