# Generated by Django 4.1.7 on 2024-10-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_remove_token_plot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='new_plot',
            new_name='plot',
        ),
    ]
